# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8084
    connection-timeout: 5000
    context-path: /frame-admin

spring:
    thymeleaf:
        cache: false
        prefix: classpath:/views/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: HTML5
    
    main:
        allow-bean-definition-overriding: true

    # 环境 dev|test|pro
    profiles:
        active: dev

    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources: # 静态资源的路径
        static-locations: classpath:/statics/,classpath:/views/
    redis:
        database: 2
        hostName: 127.0.0.1
        port: 6379
        # password:       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis-config.xml


